cmake_minimum_required(VERSION 3.20)
file(MAKE_DIRECTORY "${LOG_DIR}")
if(COMPILER_ID STREQUAL "MSVC")
  set(flags /nologo /std:c++latest /Zc:__cplusplus /Zs /DHAS_STD_LIB=1)
  set(include_flag /I)
  set(define_flag /D)
else()
  set(flags -std=c++23 -DHAS_STD_LIB=1 -fsyntax-only)
  set(include_flag -I)
  set(define_flag -D)
endif()
foreach(directory IN LISTS INCLUDE_DIRS)
  if(NOT directory STREQUAL "")
    list(APPEND flags "${include_flag}${directory}")
  endif()
endforeach()
set(valid_cases 0 6 7 12 17 18)
set(invalid_cases 1 2 3 4 5 8 9 10 11 13 14 15 16 19 20)
foreach(case IN LISTS valid_cases invalid_cases)
  execute_process(COMMAND "${CXX}" ${flags} "${define_flag}CASE_ID=${case}" "${SOURCE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
  file(WRITE "${LOG_DIR}/case-${case}.log" "${output}${errors}")
  if(case IN_LIST valid_cases)
    if(NOT result STREQUAL "0")
      message(FATAL_ERROR "Valid register case ${case} failed:\n${output}${errors}")
    endif()
  else()
    if(case EQUAL 1 OR case EQUAL 4 OR case EQUAL 10 OR case EQUAL 11
        OR case EQUAL 14 OR case EQUAL 15)
      set(diagnostic "The provided bit values have colliding bit positions in the target[.]")
    elseif(case EQUAL 2)
      set(diagnostic "The target value does not contain all the bit values provided[.]")
    elseif(case EQUAL 3)
      set(diagnostic "GREVIR_REGISTER_FIELD_OUT_OF_RANGE")
    elseif(case EQUAL 16)
      set(diagnostic "Given bitfield is not supported in the given registers[.]")
    elseif(case EQUAL 8 OR case EQUAL 9 OR case EQUAL 13 OR case EQUAL 19 OR case EQUAL 20)
      set(diagnostic "Bitfield was not contained in any of the registers provided[.]")
    else()
      set(diagnostic "Mask should not be zero[.]")
    endif()
    if(NOT result MATCHES "^[1-9][0-9]*$" OR
        NOT "${output}${errors}" MATCHES "(static assertion failed|static_assert failed)[^\n]*${diagnostic}")
      message(FATAL_ERROR "Register case ${case}: expected ${diagnostic}; got ${result}:\n${output}${errors}")
    endif()
  endif()
endforeach()
message(STATUS "Register contracts: 6 valid operations and 15 expected rejections passed")
